---
- name: 'Add Redis repository'
  apt_repository:
    repo: '{{ redis.ppa }}'
    state: 'present'
    update_cache: yes

- name: 'Install Redis package'
  apt:
    name: 'redis-server'
    state: 'latest'
    update_cache: yes

- name: 'Copy Redis configuration'
  template:
    src: 'redis.conf.j2'
    dest: '/etc/redis/redis.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
    backup: yes
  notify: 'restart redis'

- name: 'Ensure Redis is enabled & running'
  service:
    name: 'redis-server'
    state: 'started'
    enabled: yes
