---
- name: 'Add Node.js repository'
  shell: 'curl -sL {{ nodejs.repo_url }} | sudo -E bash -'
  become: no

- name: 'Install Node.js package'
  apt:
    name: 'nodejs'
    state: 'latest'
    update_cache: yes

- name: 'Install NPM global packages'
  npm:
    name: '{{ item }}'
    global: yes
    state: 'present'
  with_items: '{{ nodejs.global_packages }}'
